apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-etudiant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty-etudiant-service
  template:
    metadata:
      labels:
        app: faculty-etudiant-service
    spec:
      containers:
        - name: faculty-etudiant-service
          image: faculty_management-faculty-etudiant-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_SERVICE_URL
              value: "http://faculty-config-service:9999"
            - name: DISCOVERY_SERVICE_URL
              value: "http://faculty-discovery-service:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: faculty-etudiant-service
spec:
  type: ClusterIP
  selector:
    app: faculty-etudiant-service
  ports:
    - port: 8082
      targetPort: 8082
