apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty-gateway-service
  template:
    metadata:
      labels:
        app: faculty-gateway-service
    spec:
      containers:
        - name: faculty-gateway-service
          image: faculty_management-faculty-gateway-service:latest
          ports:
            - containerPort: 8888
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://faculty-discovery-service:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: faculty-gateway-service
spec:
  type: NodePort    # si tu veux exposer le gateway depuis l'extérieur du cluster
  selector:
    app: faculty-gateway-service
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30080
